-- Supabase seed: questions table
-- columns: id (int), intelligence (text), text (text)

INSERT INTO questions (id, intelligence, text) VALUES (1, 'linguistic', '책이나 긴 글을 읽을 때 시간 가는 줄 모를 때가 많다.');
INSERT INTO questions (id, intelligence, text) VALUES (2, 'linguistic', '내 생각을 말이나 글로 정확히 표현하는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (3, 'linguistic', '새로운 단어나 표현을 알게 되면 직접 써보고 싶어진다.');
INSERT INTO questions (id, intelligence, text) VALUES (4, 'linguistic', '친구들 사이에서 ''말 잘한다'' 또는 ''글 잘 쓴다''는 말을 들은 적이 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (5, 'linguistic', '토론이나 발표 자리에서 에너지를 얻는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (6, 'linguistic', '같은 내용도 어떻게 말하느냐에 따라 다르게 들린다는 점이 흥미롭다.');
INSERT INTO questions (id, intelligence, text) VALUES (7, 'linguistic', '외국어를 배울 때 어휘나 표현이 비교적 잘 외워지는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (8, 'logical', '어떤 현상을 보면 ''왜 그럴까?''의 원인을 끝까지 따져보고 싶어진다.');
INSERT INTO questions (id, intelligence, text) VALUES (9, 'logical', '복잡한 문제를 단계별로 쪼개어 푸는 것이 즐겁다.');
INSERT INTO questions (id, intelligence, text) VALUES (10, 'logical', '숫자나 데이터를 보면 패턴을 찾아보게 된다.');
INSERT INTO questions (id, intelligence, text) VALUES (11, 'logical', '논리적으로 앞뒤가 맞지 않는 말을 들으면 바로 알아챈다.');
INSERT INTO questions (id, intelligence, text) VALUES (12, 'logical', '퍼즐, 추리, 전략 게임을 좋아한다.');
INSERT INTO questions (id, intelligence, text) VALUES (13, 'logical', '결정을 내릴 때 감보다는 근거와 데이터를 먼저 찾는다.');
INSERT INTO questions (id, intelligence, text) VALUES (14, 'logical', '어떤 일의 절차를 정리하거나 규칙을 만드는 것이 자연스럽다.');
INSERT INTO questions (id, intelligence, text) VALUES (15, 'spatial', '머릿속으로 사물을 회전시키거나 입체로 그려볼 수 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (16, 'spatial', '처음 가본 길도 한 번 가면 잘 기억하는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (17, 'spatial', '그림, 사진, 영상, 디자인 등 시각적인 것에 관심이 많다.');
INSERT INTO questions (id, intelligence, text) VALUES (18, 'spatial', '공간이나 방을 어떻게 배치할지 상상하는 게 즐겁다.');
INSERT INTO questions (id, intelligence, text) VALUES (19, 'spatial', '글보다 이미지·다이어그램으로 설명할 때 이해가 빠르다.');
INSERT INTO questions (id, intelligence, text) VALUES (20, 'spatial', '색감, 비율, 구도 같은 시각적 균형에 민감한 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (21, 'spatial', '지도를 보고 길을 찾는 데 큰 어려움이 없다.');
INSERT INTO questions (id, intelligence, text) VALUES (22, 'bodily', '몸을 움직이는 활동(운동·춤·만들기)을 할 때 가장 활기가 돈다.');
INSERT INTO questions (id, intelligence, text) VALUES (23, 'bodily', '새로운 동작이나 손기술을 비교적 빨리 익히는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (24, 'bodily', '가만히 앉아 있는 것보다 움직이며 생각할 때 아이디어가 잘 떠오른다.');
INSERT INTO questions (id, intelligence, text) VALUES (25, 'bodily', '손으로 무언가를 만들거나 고치는 일을 즐긴다.');
INSERT INTO questions (id, intelligence, text) VALUES (26, 'bodily', '내 몸의 컨디션이나 자세 변화를 잘 알아차린다.');
INSERT INTO questions (id, intelligence, text) VALUES (27, 'bodily', '직접 해보지 않으면 감이 잘 오지 않는다.');
INSERT INTO questions (id, intelligence, text) VALUES (28, 'bodily', '몸을 사용하는 일에서 성취감을 크게 느낀다.');
INSERT INTO questions (id, intelligence, text) VALUES (29, 'musical', '노래나 멜로디를 한두 번만 들어도 잘 따라 부른다.');
INSERT INTO questions (id, intelligence, text) VALUES (30, 'musical', '일상에서 머릿속에 음악이 자주 흐른다.');
INSERT INTO questions (id, intelligence, text) VALUES (31, 'musical', '소리의 미묘한 차이(음정·박자·음색)를 잘 구분한다.');
INSERT INTO questions (id, intelligence, text) VALUES (32, 'musical', '음악을 들으면 감정이나 장면이 생생하게 떠오른다.');
INSERT INTO questions (id, intelligence, text) VALUES (33, 'musical', '분위기에 맞는 음악을 고르는 데 자신이 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (34, 'musical', '리듬에 맞춰 몸이 자연스럽게 반응한다.');
INSERT INTO questions (id, intelligence, text) VALUES (35, 'musical', '음 이탈이나 박자 어긋남이 들리면 신경이 쓰인다.');
INSERT INTO questions (id, intelligence, text) VALUES (36, 'interpersonal', '처음 만난 사람과도 비교적 편안하게 대화한다.');
INSERT INTO questions (id, intelligence, text) VALUES (37, 'interpersonal', '사람들의 표정·말투에서 감정을 잘 읽어내는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (38, 'interpersonal', '갈등 상황에서 양쪽 입장을 조율하는 역할을 자주 맡는다.');
INSERT INTO questions (id, intelligence, text) VALUES (39, 'interpersonal', '누군가의 고민을 들어주는 일이 부담스럽지 않다.');
INSERT INTO questions (id, intelligence, text) VALUES (40, 'interpersonal', '모임에서 분위기를 살피고 흐름을 조율하는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (41, 'interpersonal', '사람을 만나고 나면 에너지가 충전되는 느낌이 든다.');
INSERT INTO questions (id, intelligence, text) VALUES (42, 'interpersonal', '팀으로 일할 때 더 좋은 결과가 나온다고 느낀다.');
INSERT INTO questions (id, intelligence, text) VALUES (43, 'intrapersonal', '내가 왜 그런 감정을 느끼는지 스스로 설명할 수 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (44, 'intrapersonal', '혼자 생각을 정리하는 시간이 꼭 필요하다.');
INSERT INTO questions (id, intelligence, text) VALUES (45, 'intrapersonal', '내 강점과 약점을 비교적 객관적으로 알고 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (46, 'intrapersonal', '중요한 결정을 할 때 내 가치관을 먼저 떠올린다.');
INSERT INTO questions (id, intelligence, text) VALUES (47, 'intrapersonal', '일기·메모·기록 등으로 자기 생각을 정리하는 습관이 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (48, 'intrapersonal', '남의 기준보다 내 기준으로 살고 싶다는 욕구가 강하다.');
INSERT INTO questions (id, intelligence, text) VALUES (49, 'intrapersonal', '내가 어떤 상황에서 행복하고 지치는지 잘 안다.');
INSERT INTO questions (id, intelligence, text) VALUES (50, 'naturalist', '자연(식물·동물·날씨·풍경)을 관찰하는 것이 즐겁다.');
INSERT INTO questions (id, intelligence, text) VALUES (51, 'naturalist', '사물이나 현상을 분류·체계화하는 일에 흥미가 있다.');
INSERT INTO questions (id, intelligence, text) VALUES (52, 'naturalist', '환경·생태·지속가능성 같은 주제에 관심이 많다.');
INSERT INTO questions (id, intelligence, text) VALUES (53, 'naturalist', '자연 속에 있을 때 마음이 가장 편안하다.');
INSERT INTO questions (id, intelligence, text) VALUES (54, 'naturalist', '동식물의 종류나 특징을 잘 알아보는 편이다.');
INSERT INTO questions (id, intelligence, text) VALUES (55, 'naturalist', '작은 변화(계절·기후·생물의 상태)를 민감하게 알아차린다.');
INSERT INTO questions (id, intelligence, text) VALUES (56, 'naturalist', '음식 재료, 식물, 광물 등 자연에서 온 것들의 차이를 구분하는 데 흥미가 있다.');
